/**
 * Shared version footer.
 * Injects build/version info into every page that includes this script.
 *
 * Commit metadata comes from version.json, which is generated by the
 * GitHub Pages deploy workflow. When that file is missing (local file://
 * or a plain clone), it falls back to the GitHub API so the footer still
 * shows the latest commit on the deployed branch.
 */
(function () {
    'use strict';

    const APP_VERSION = '1.6.0';
    const REPO = 'aiforgewolf/territorial-vote';

    const STYLES = `
        .app-version-footer {
            margin: 40px auto 0;
            padding: 18px 20px 26px;
            max-width: 1400px;
            border-top: 1px solid rgba(255, 255, 255, 0.1);
            text-align: center;
            font-size: 0.8rem;
            line-height: 1.9;
            color: #a0a0a0;
        }
        .app-version-footer .avf-row {
            display: flex;
            flex-wrap: wrap;
            gap: 8px 18px;
            justify-content: center;
            align-items: center;
        }
        .app-version-footer .avf-item {
            white-space: nowrap;
        }
        .app-version-footer .avf-label {
            opacity: 0.7;
            margin-right: 4px;
        }
        .app-version-footer .avf-value {
            color: #e0e0e0;
            font-weight: 600;
        }
        .app-version-footer .avf-version {
            color: #ffd700;
            font-weight: 700;
        }
        .app-version-footer a.avf-commit {
            color: #4da6ff;
            font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
            font-weight: 600;
            text-decoration: none;
            border-bottom: 1px dotted rgba(77, 166, 255, 0.5);
        }
        .app-version-footer a.avf-commit:hover {
            color: #80c0ff;
        }
        .app-version-footer .avf-subject {
            display: block;
            margin-top: 6px;
            opacity: 0.65;
            font-style: italic;
            overflow-wrap: anywhere;
        }
    `;

    function formatDate(value) {
        if (!value) return null;
        const date = new Date(value);
        if (isNaN(date.getTime())) return null;
        return date.toLocaleString(undefined, {
            year: 'numeric',
            month: 'short',
            day: '2-digit',
            hour: '2-digit',
            minute: '2-digit'
        });
    }

    function escapeHtml(text) {
        const div = document.createElement('div');
        div.textContent = text;
        return div.innerHTML;
    }

    function render(info) {
        const style = document.createElement('style');
        style.textContent = STYLES;
        document.head.appendChild(style);

        const footer = document.createElement('div');
        footer.className = 'app-version-footer';

        const items = [
            `<span class="avf-item"><span class="avf-label">Version</span><span class="avf-version">v${escapeHtml(APP_VERSION)}</span></span>`
        ];

        const released = formatDate(info.commitDate) || formatDate(info.buildDate);
        if (released) {
            items.push(`<span class="avf-item"><span class="avf-label">Released</span><span class="avf-value">${escapeHtml(released)}</span></span>`);
        }

        if (info.sha) {
            const short = info.sha.substring(0, 7);
            const url = `https://github.com/${REPO}/commit/${info.sha}`;
            items.push(`<span class="avf-item"><span class="avf-label">Commit</span><a class="avf-commit" href="${url}" target="_blank" rel="noopener">${escapeHtml(short)}</a></span>`);
        }

        if (info.branch) {
            items.push(`<span class="avf-item"><span class="avf-label">Branch</span><span class="avf-value">${escapeHtml(info.branch)}</span></span>`);
        }

        items.push(`<span class="avf-item"><a class="avf-commit" href="https://github.com/${REPO}" target="_blank" rel="noopener">GitHub</a></span>`);

        let html = `<div class="avf-row">${items.join('')}</div>`;
        if (info.subject) {
            html += `<span class="avf-subject">${escapeHtml(info.subject)}</span>`;
        }

        footer.innerHTML = html;
        document.body.appendChild(footer);
    }

    function fromGitHubApi() {
        return fetch(`https://api.github.com/repos/${REPO}/commits?per_page=1`)
            .then(res => (res.ok ? res.json() : Promise.reject(new Error('api'))))
            .then(commits => {
                const commit = Array.isArray(commits) ? commits[0] : null;
                if (!commit) throw new Error('no commits');
                return {
                    sha: commit.sha,
                    commitDate: commit.commit && commit.commit.committer && commit.commit.committer.date,
                    subject: commit.commit && commit.commit.message
                        ? commit.commit.message.split('\n')[0]
                        : null
                };
            });
    }

    function load() {
        fetch('version.json', { cache: 'no-cache' })
            .then(res => (res.ok ? res.json() : Promise.reject(new Error('no version.json'))))
            .catch(fromGitHubApi)
            .catch(() => ({}))
            .then(render)
            .catch(() => render({}));
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', load);
    } else {
        load();
    }
})();
